# Generated by Django 5.1.6 on 2025-02-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
